### ISSUE TITLE
Parts cost needs correcting for some Kontainers & honey badger cargo pods

### ISSUE THREAD

**Issue by AcidEric** [BobPalmer/FTT#64] opened 2015-02-22 23:34 UTC
The prices are in negative numbers in SPH/VAB for some of the Kontainers if you empty them of resources this affects the Ore, Rocket part, Metal, Chemical, & Polymer Kontainers, Kontainer MKII's and Kontainer pods. 

The same thing is happening to the Ore, Mono propellant, Uraninite, & rocket parts HoneyBadger Cargo pods. Both the regular and Jumbo versions of all 4 resources.

**Comment by TCFirebird** [comment] 2015-02-23 00:37
I believe this is a duplicate of issue #53 and has been corrected by commit #57

**Closed** 2017-03-16 21:26 UTC
Labels: Investigate
